name: Manual Test

on:
    workflow_dispatch:
        inputs:
            branch:
                description: "Branch to test"
                required: true
                default: "main"
                type: string

jobs:
    backend-tests:
        name: Backend Tests
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./serverless
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.branch }}

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: "./serverless/package-lock.json"

            - name: Install dependencies
              run: npm ci

            - name: Run backend tests
              run: npm test

            - name: Run linting
              run: npm run lint

            - name: Check TypeScript compilation
              run: npx tsc --noEmit

            - name: Generate test coverage report
              run: npm run test:coverage
